### ISSUE TITLE
RFE: Update the minimum Ansible version and sync this to other roles

### ISSUE THREAD

**Issue by tyll** [linux-system-roles/template#22]
The minimum Ansible version in

https://github.com/linux-system-roles/template/blob/d2239c750e3f6f471bcfcc4610246e0a0dbb55b1/meta/main.yml#L24

looks like something that should be updated and synced to roles. Other values like platform versions, probably, too.

**Comment by pcahyna** [comment]
This could be difficult to sync, because each role modifies this file and adds something. Even more difficult for platform versions, because the differences are intentional (some roles intentionally do not supoort EL 6, for example).

**Comment by richm** [comment]
This might be one of those cases like `molecule/default/molecule.yml` where the sync-template script will have to deal with the fact that the individual role may have customized the file, and whoever runs the sync script will have to manually merge in changes.  This also means the role developer will need to add some sort of comment to the yaml to indicate that the version setting is intentional.
